---
- name: installs nginx
  apt: pkg=nginx

- name: removes the default app
  file: path=/etc/nginx/sites-enabled/default state=absent

- name: adds http conf
  template: src=http.conf.j2 dest=/etc/nginx/conf.d/http.conf force=true
  notify: restart nginx

- name: adds app conf
  template: src=nginx.conf.j2 dest=/etc/nginx/sites-enabled/{{app_name}} force=true
  vars:
    ssl_on: false
  notify: restart nginx

- name: enable nginx stats
  template: src=nginx-stats.conf.j2 dest=/etc/nginx/sites-enabled/nginx-stats.conf 
  notify: restart nginx

- name: check nginx
  command: nginx -t
  register: nginx_status
- debug: msg=nginx_status
