---
- hosts: database
  become: true
  roles:
    - dev
    - postgresql-server

- hosts: web
  become: true
  roles:
    - dev
    - git
    - postgresql-client
    - rails
    - puma
    - nginx
    - redis
    - sidekiq
    - ssl
