---
- hosts: database
  become: true
  roles:
    - dev
    - postgresql-server

- hosts: web
  become: true
  roles:
    - dev
    - git
    - swap
    - postgresql-client
    - rails
    - puma
    - { role: nginx,  ssl_on: false }
    - redis
    - sidekiq
    - ssl
