---
- name: installs rails
  command: gem install rails creates=/usr/local/bin/rails

- name: configures logrotate
  template: src=logrotate.j2 dest=/etc/logrotate.d/app mode=644

- name: clones repository
  git: repo={{repository}} dest={{app_path}} update=no accept_hostkey=yes

- name: changes app path owner
  file: path={{app_path}} recurse=yes owner={{user}}

- name: Create config/database.yml
  template: src=database.yml.j2 dest={{ app_path }}/config/database.yml owner={{ user }} mode=0600 backup=yes

- name: bundle install
  become_user: "{{ user }}"
  command: bundle install --deployment chdir={{ app_path }}
  register: bundler

- name: setups database
  become_user: "{{ user }}"
  command: bundle exec rake db:migrate RAILS_ENV={{rails_env}} chdir={{app_path}}

- name: compile assets
  become_user: "{{ user }}"
  command: bundle exec rake assets:precompile RAILS_ENV={{ rails_env }} chdir={{ app_path }}
