- name: installs sidekiq
  command: gem install sidekiq creates=/usr/local/bin/{{ sidekiq_app_name }}

- name: adds sidekiq init script
  template: src=sidekiq.j2 dest=/etc/init.d/{{ sidekiq_app_name }} mode=755

- name: adds sidekiq to upstart
  command: update-rc.d -f {{ sidekiq_app_name }} defaults
  notify: restart sidekiq
