---
- name: installs sidekiq
  command: gem install sidekiq creates=/usr/local/bin/sidekiq

- name: ensure sidekiq init.d config is created
  template: src=initd_sidekiq.j2 dest=/etc/init.d/sidekiq mode=0755

- name: ensure sidekiq starts on a fresh reboot
  service: name=sidekiq state=started enabled=yes
