---
- name: update project source
  git: repo={{repository}} dest={{app_path}} version={{git_branch}} accept_hostkey=yes
  register: git
  changed_when: "git.after|default('after') != git.before|default('before')"

- name: install gems with bundler
  become_user: "{{ user }}"
  command: bundle install --deployment chdir={{ app_path }}
  register: bundler
  # when: git.changed

- debug: msg="Missing puma gem in Gemfile"
  when: bundler is defined and bundler.stdout.find("puma") == -1

- debug: msg="Missing sidekiq gem in Gemfile"
  when: bundler is defined and bundler.stdout.find("sidekiq") == -1

- name: migrate the database
  become_user: "{{ user }}"
  command: bundle exec rake db:migrate RAILS_ENV={{ rails_env }} chdir={{ app_path }}
  when: git.changed

- name: compile assets
  become_user: "{{ user }}"
  command: bundle exec rake assets:precompile RAILS_ENV={{ rails_env }} chdir={{ app_path }}
  when: git.changed

# - name: restart puma
#   service: name=puma state=restarted enabled=yes

- name: ensure sidekiq restarts
  service: name=sidekiq state=restarted enabled=yes
  # when: git.changed

- name: registers puma pid
  command: cat {{app_path}}/tmp/pids/puma.pid chdir={{ app_path }}
  register: puma_pid

- name: restart puma
  command: kill -USR2 {{ puma_pid.stdout }}

# - include_vars: ../../sidekiq/defaults/main.yml
# - name: restart sidekiq
#   service: name={{ sidekiq_app_name }} state=restarted enabled=yes
#   become_user: "root"

