

- name: update project source
  git: repo={{repository}} dest={{app_path}} version={{git_branch}} accept_hostkey=yes
  notify:
     - restart puma
     - restart sidekiq
  register: git
# - debug: msg='Updated repo from {{ git.before }} to {{ git.after }}'

- name: install gems with bundler
  become_user: "{{ user }}"
  command: bundle install --deployment chdir={{ app_path }}
  register: bundler

- name: migrate the database
  become_user: "{{ user }}"
  command: bundle exec rake db:migrate RAILS_ENV={{ rails_env }} chdir={{ app_path }}

- name: compile assets
  become_user: "{{ user }}"
  command: bundle exec rake assets:precompile RAILS_ENV={{ rails_env }} chdir={{ app_path }}

- debug: msg="Missing puma gem in Gemfile"
  when: bundler.stdout.find("puma") == -1

- name: restart puma
  service: name=puma state=restarted

- debug: msg="Missing puma gem in Sidekiq"
  when: bundler.stdout.find("sidekiq") == -1

- include_vars: ../../sidekiq/defaults/main.yml
- name: restart sidekiq
  service: name={{ sidekiq_app_name }} state=restarted
