- name: installs puma
  command: gem install puma creates=/usr/local/bin/puma

- name: adds puma init script
  template: src=puma.j2 dest=/etc/init.d/puma mode=755

- name: adds puma runner
  template: src=run-puma.j2 dest=/usr/local/bin/run-puma mode=755

- name: adds puma conf
  template: src=puma.conf.j2 dest=/etc/puma.conf mode=644

- name: adds puma app conf
  template: src=puma.rb.j2 dest={{puma_config_path}} mode=644

- name: creates puma pid folder
  file: path={{app_path}}/tmp/pids owner={{user}} group={{user}} state=directory

- name: adds puma to traditional sysvinit scripts upstart
  become_user: 'root'
  command: update-rc.d -f puma defaults

- name: start puma
  service: name=puma state=started
# - name: adds puma to upstart
#   template: src=upstart.conf.j2 dest=/etc/init/puma.conf
#   notify: restart puma
