---
- name: installs psql
  apt: pkg=postgresql

- name: installs extensions
  apt: pkg=postgresql-contrib

- name: install psycopg2
  apt: pkg=python-psycopg2

- name: grants access for database to user
  become_user: postgres
  postgresql_user: name={{db_user}} password={{db_password}} role_attr_flags=SUPERUSER,LOGIN,CREATEDB state=present

- name: Create postgresql database
  postgresql_db: name={{ db_name }} owner={{ db_user }}
  become_user: postgres
  
- name: Create postgresql test database
  postgresql_db: name={{ db_name }}_test owner={{ db_user }}
  become_user: postgres
